#!/bin/bash
#$ -l h_rt=12:0:0
#$ -l h_vmem=8G
#$ -pe smp 8
#$ -l gpu=1
#$ -cwd
#$ -j y
#$ -l rocky

echo $SGE_HGR_gpu
set -e

# Replace the following line with a program or command
cd /data/home/ec23709/project/Retrieval
source ./../ReID/reid/bin/activate
python train.py --config_file configs/person/train.yml

# Generated by Job Script Builder on 2025-03-07
# For assistance, please email its-research-support@qmul.ac.uk
# Please cite use of Apocrita in your Research
# See https://docs.hpc.qmul.ac.uk/using/citing/ for details